# Flexible GraphRAG Application Stack
services:
  # Backend FastAPI service
  flexible-graphrag-backend:
    build: 
      context: ../../flexible-graphrag
      dockerfile: Dockerfile
    container_name: flexible-graphrag-backend
    env_file:
      - ../../flexible-graphrag/.env     # Load main configuration first
      - ../docker.env                    # Override with host.docker.internal addresses
    ports:
      - "8000:8000"
    volumes:
      - ../../sample-docs:/app/sample_docs:ro
      - upload_data:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Angular UI
  flexible-graphrag-ui-angular:
    build:
      context: ../../flexible-graphrag-ui/frontend-angular
      dockerfile: Dockerfile
    container_name: flexible-graphrag-angular
    environment:
      - API_BASE_URL=/api
    ports:
      - "4200:4200"
    depends_on:
      - flexible-graphrag-backend
    restart: unless-stopped

  # React UI  
  flexible-graphrag-ui-react:
    build:
      context: ../../flexible-graphrag-ui/frontend-react
      dockerfile: Dockerfile
    container_name: flexible-graphrag-react
    environment:
      - VITE_API_BASE_URL=/api
    ports:
      - "3000:3000"
    depends_on:
      - flexible-graphrag-backend
    restart: unless-stopped

  # Vue UI
  flexible-graphrag-ui-vue:
    build:
      context: ../../flexible-graphrag-ui/frontend-vue
      dockerfile: Dockerfile
    container_name: flexible-graphrag-vue
    environment:
      - VITE_API_BASE_URL=/api
    ports:
      - "5173:5173"
    depends_on:
      - flexible-graphrag-backend
    restart: unless-stopped

# Self-contained service definitions

volumes:
  upload_data:
    driver: local