# Kuzu Graph Database with API Server
services:
  kuzu-api-server:
    image: kuzudb/api-server:latest
    container_name: flexible-graphrag-kuzu
    ports:
      - "8001:8000"    # Kuzu API Server (avoiding conflict with backend at 8000)
    volumes:
      - kuzu_data:/database
    environment:
      - MODE=READ_WRITE
      - KUZU_BUFFER_POOL_SIZE=1073741824  # 1GB buffer pool
      - CROSS_ORIGIN=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  kuzu-explorer:
    image: kuzudb/explorer:latest
    container_name: flexible-graphrag-kuzu-explorer
    ports:
      - "8002:8000"    # Kuzu Explorer web interface
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  kuzu_data:
