# OpenSearch Search Engine
services:
  opensearch:
    image: opensearchproject/opensearch:2.12.0
    container_name: flexible-graphrag-opensearch
    environment:
      - discovery.type=single-node
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
      - cluster.name=flexible-graphrag-opensearch
      - node.name=opensearch-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    ports:
      - "9201:9200"    # Changed port to avoid conflict with Elasticsearch
      - "9301:9300"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.12.0
    container_name: flexible-graphrag-opensearch-dashboards
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - server.host=0.0.0.0
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - "5602:5601"    # Use different port to avoid conflict with Kibana
    depends_on:
      opensearch:
        condition: service_healthy
    restart: unless-stopped

volumes:
  opensearch_data:
