# Pinecone Vector Database Configuration
# 
# NOTE: Pinecone is a managed serverless cloud service - no local database container needed.
# This configuration provides an info page with links to the official Pinecone Console.
#
# Pinecone Configuration Requirements:
# - VECTOR_DB=pinecone
# - VECTOR_DB_CONFIG={"api_key": "your_pinecone_api_key", "region": "us-east-1", "cloud": "aws", "index_name": "hybrid-search", "metric": "cosine"}
# - Dimension is auto-detected from your embedding model (e.g., 1536 for OpenAI, 384 for Ollama default)
#
# Sign up at https://pinecone.io (free starter plan available)
# Official Dashboard: https://app.pinecone.io

services:
  pinecone-ui:
    # Info page with links to official Pinecone Console
    # Serves static HTML from ../pinecone-info/
    image: nginx:alpine
    container_name: flexible-graphrag-pinecone-info
    ports:
      - "3004:80"  # Pinecone info dashboard
    volumes:
      - ../pinecone-info:/usr/share/nginx/html
    #restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

